# Generated by Django 5.2.6 on 2025-09-17 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0003_initial"),
        ("cars", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="owner",
            field=models.ForeignKey(
                help_text="Fleet manager who owns this car",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_cars",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="carimage",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="cars.car",
            ),
        ),
        migrations.AddField(
            model_name="carreview",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="carreview",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="cars.car",
            ),
        ),
        migrations.AddField(
            model_name="carreview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(
                fields=["status", "location"], name="cars_car_status_479ba6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(
                fields=["make", "model"], name="cars_car_make_3ceb9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(
                fields=["price_per_day"], name="cars_car_price_p_df7c78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(
                fields=["owner", "status"], name="cars_car_owner_i_8eca57_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="car",
            constraint=models.CheckConstraint(
                condition=models.Q(("price_per_day__gt", 0)),
                name="positive_price_per_day",
            ),
        ),
        migrations.AddConstraint(
            model_name="car",
            constraint=models.CheckConstraint(
                condition=models.Q(("year__gte", 1900)), name="valid_year"
            ),
        ),
        migrations.AddIndex(
            model_name="carimage",
            index=models.Index(
                fields=["car", "is_primary"], name="cars_carima_car_id_4b6ae5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carreview",
            index=models.Index(
                fields=["car", "is_approved"], name="cars_carrev_car_id_864366_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carreview",
            index=models.Index(fields=["rating"], name="cars_carrev_rating_889bb7_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="carreview",
            unique_together={("car", "user", "booking")},
        ),
    ]
